corpos_build_root: build
nvidia_dsc_url: http://archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-595/nvidia-graphics-drivers-595_595.84-0ubuntu0.26.04.1.dsc
nvidia_version_suffix: +0corpos1
corpos_control_x_flags:
  - "XSBC-Corpos: true"
  - "XSBC-Git-Branch: main"
nvidia_source_files: []
nvidia_dpkg_source_no_check: true
nvidia_install_build_deps: true
nvidia_test_build: true