- name: Calculate and set driver source variables
  ansible.builtin.set_fact:
    dsc_file: "{{ nvidia_dsc_url | basename }}"
    source_dirname: "{{ (nvidia_dsc_url | basename) | splitext | first }}"
    source_dir: "{{ nvidia_build_dir }}/{{ (nvidia_dsc_url | basename) | splitext | first }}"

- name: Ensure build directory exists
  ansible.builtin.file:
    path: "{{ nvidia_build_dir }}"
    state: directory

- name: Git init
  ansible.builtin.include_tasks: git.yml

- name: Download sources
  ansible.builtin.include_tasks: download.yml

- name: Unpack source with dpkg-source
  ansible.builtin.include_tasks: unpack.yml

- name: Strip Ubuntu-specific packaging
  ansible.builtin.include_tasks: strip.yml

- name: Modify for the Debian build
  ansible.builtin.include_tasks: modify.yml

- name: Test build ability
  ansible.builtin.include_tasks: build.yml